- name: Instalar y Configurar OCI CLI vía Pip
      env:
        OCI_USER: ${{ secrets.OCI_USER_OCID }}
        OCI_TENANCY: ${{ secrets.OCI_TENANCY_OCID }}
        OCI_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
        OCI_REGION: "mx-monterrey-1"
        OCI_KEY_TEXT: ${{ secrets.OCI_API_KEY }}
      run: |
        # Instala OCI CLI usando pip
        pip install oci-cli
        
        # Configura las credenciales
        mkdir -p ~/.oci
        echo "$OCI_KEY_TEXT" > ~/.oci/oci_api_key.pem
        chmod 600 ~/.oci/oci_api_key.pem
        
        cat << EOF > ~/.oci/config
        [DEFAULT]
        user=$OCI_USER
        fingerprint=$OCI_FINGERPRINT
        tenancy=$OCI_TENANCY
        region=$OCI_REGION
        key_file=/home/runner/.oci/oci_api_key.pem
        EOF
        
        chmod 600 ~/.oci/config
